### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Nublys**

### CODE REVIEW

**Comment by Nublys** [comment]
Sorry! Still learning github, this a per-mature pull!

**Comment by prayag17** [comment]
I will suggest you don't work on this rightnow cause I am working on to sassify jellyflix just like jellyskin

**Comment by Nublys** [comment]
> I will suggest you don't work on this rightnow cause I am working on to sassify jellyflix just like jellyskin

I won't do anything upstream just a few easy fixes are making this version unusable on my phone for now. Excited for the sassify version though!

**Comment by prayag17** [comment]
Ohk nice

**Pull request closed without merging**
